/**
 * Generate Astro-aware service worker (no /_next/* assumptions).
 * Writes public/sw.js consumed by Astro build → dist.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(__dirname, '../public/sw.js');

const sw = `/* UnicodeKruti Astro POC service worker — /_astro/* aware.
 * Generated by scripts/generate-sw.mjs. Do not copy Next Workbox /_next manifests.
 */
const CACHE_VERSION = 'uk-astro-poc-v1';
const PRECACHE = [
  '/',
  '/krutidev-to-unicode-converter/',
  '/about-us/',
  '/font-download/',
  '/contact-us/',
  '/manifest.json',
  '/favicon.ico',
  '/logo.svg',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_VERSION).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

function isAstroAsset(url) {
  return url.pathname.startsWith('/_astro/');
}

function isStaticAsset(url) {
  return (
    url.pathname.startsWith('/fonts/') ||
    url.pathname.startsWith('/icons/') ||
    url.pathname.startsWith('/images/') ||
    url.pathname.startsWith('/og/') ||
    url.pathname === '/manifest.json' ||
    url.pathname === '/logo.svg' ||
    url.pathname === '/favicon.ico' ||
    url.pathname === '/apple-touch-icon.png' ||
    url.pathname === '/pdf.worker.min.mjs'
  );
}

function isDocumentNav(request, url) {
  if (request.destination !== 'document') return false;
  const path = url.pathname.replace(/\\/$/, '') || '/';
  return (
    path === '/' ||
    path === '/krutidev-to-unicode-converter' ||
    path === '/about-us' ||
    path === '/font-download' ||
    path === '/contact-us'
  );
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Never use Next image optimizer routes
  if (url.pathname.startsWith('/_next/')) {
    return;
  }

  if (isAstroAsset(url) || isStaticAsset(url)) {
    event.respondWith(
      caches.open(CACHE_VERSION).then(async (cache) => {
        const cached = await cache.match(request);
        if (cached) return cached;
        const res = await fetch(request);
        if (res.ok) cache.put(request, res.clone());
        return res;
      })
    );
    return;
  }

  if (isDocumentNav(request, url)) {
    event.respondWith(
      (async () => {
        try {
          const res = await fetch(request);
          const cache = await caches.open(CACHE_VERSION);
          if (res.ok) cache.put(request, res.clone());
          return res;
        } catch {
          const cached = await caches.match(request);
          if (cached) return cached;
          return caches.match('/');
        }
      })()
    );
  }
});
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, sw);
console.log('[generate-sw] wrote', out);
